project:
  type: website
  render:
    - "*.qmd" # render all qmd files
    - "links.md" # including a couple other files that may be useful
    - "sharing.md"


    - "data/2025/readme.md"
    - "data/2025/*/readme.md" # render each md file for 2025
    - "data/2024/readme.md"
    - "data/2024/*/readme.md"
  output-dir: docs

website:
  # site-url: {domain name to be used}
  title: "TidyTuesday"
  search: false
  navbar: true
  sidebar:
    style: docked
    contents:
      - section: "TidyTuesday"
        href: index.qmd
        contents:
          - text: "About"
            href: about.qmd
          - text: "Links"
            href: links.html
          - text: "Sharing"
            href: sharing.html
      - section: "Datasets"
        contents:
          - text: "2025 Data"
            href: data/2025/readme.html
          - text: "2024 Data"
            href: data/2024/readme.html
            
format:
  html:
    theme:
      - cosmo
      - brand
    page-layout: full
    css: styles.css
    toc: true
