project:
  type: website
  render:
    - "*.qmd" # render all qmd files
    # - "*.md" # render all md files
    - "links.md" # manually including the files linked to from README
    - "sharing.md"
    - "dataset_announcements.md"
    - ".github/pr_instructions.md"
    - ".github/CONTRIBUTING.md"
    - "data/2025/readme.md"
    - "data/2025/*/readme.md" # render each md file for 2025
    - "data/2024/readme.md"
    - "data/2024/*/readme.md"
  output-dir: docs

website:
  # site-url: {domain name to be used}
  title: "TidyTuesday"
  search: true
  navbar: true
  sidebar:
    logo: "static/tt_hex.png"
    style: docked
    contents:
      - about.qmd
      - sharing.md
      - links.md
      - section: "Datasets"
        contents:
          - text: "2025"
            href: data/2025/readme.md
          - text: "2024"
            href: data/2024/readme.md
            
format:
  html:
    theme:
      - cosmo
      - brand
    page-layout: full
    css: styles.css
    toc: true

# quarto commands:
# quarto preview
# quarto render

# if there are issues with previews sometimes this can help:
# quarto preview --render all --no-watch-inputs
